import "./globals.css";
import type { Metadata } from "next";
import StyledComponentsRegistry from "./lib/AntdRegistry";
import { ConfigProvider, Layout } from "antd";
import theme from "./theme/themeConfig";
import MainHeader from "./components/MainHeader/MainHeader";
import { AppLogo } from "./components/AppLogo/AppLogo";
import { Contact } from "./components/Contact/Contact";
import { AppNavigation } from "./components/AppNavigation/AppNavigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body style={{ fontFamily: "Carlito!important" }}>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme}>
            <Layout>
              <MainHeader
                AppLogo={<AppLogo />}
                Contact={<Contact />}
                AppNavigation={<AppNavigation />}
              />
              {children}
            </Layout>
          </ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
